- name: "Update all packages to the latest version"
  apt: upgrade=full

- name: "Adding keys for non public programs"
  apt_key: url={{ item }} state=present
  with_items:
  - https://download.spotify.com/debian/pubkey.gpg
  - https://download.docker.com/linux/ubuntu/gpg

- name: "Adding repos for non public programs"
  apt_repository: repo={{ item }} codename=bionic state=present
  with_items:
  - deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  - deb http://repository.spotify.com stable non-free
  - ppa:amanusk/python-s-tui

- name: "Getting deb packages"
  get_url: url={{ item['url'] }} dest={{ item['dest'] }} mode=0644 timeout=20
  with_items:
    - url: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.4.2-amd64.deb
      dest: /tmp/slack.deb

- name: "Installing deb packages"
  apt: deb={{ item }} state=present
  with_items:
    - /tmp/slack.deb

- name: "Installing core packages"
  apt: pkg={{ packages }} state=present update_cache=yes
  vars:
    packages:
    # system and helpers
    - i3-wm
    - dmenu
    - htop
    - pavucontrol
    - python3-s-tui
    - stress
    - python-psutil
    - rlwrap

    # backup
    - backintime-common
    - backintime-qt4

      # other apps
    - spotify-client
    - vlc
    - slack-desktop
