cloud_tools_path: "{{ ansible_env['HOME'] }}/software/cloud"

os: linux

versions:
  gcloud: 289.0.0
  helm: v3.1.2
  kubectl: v1.18.0
  kubectx: v0.8.0
  kubeps1: v0.7.0
  minikube: v1.9.2
  mkcert: v1.4.1
  stern: 1.11.0
  spruce: v1.25.2
  terraform: 0.12.24
  vault: 1.4.0

tools:
  binaries:
  - name: kubectl
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ versions['kubectl'] }}/bin/{{ os }}/amd64/kubectl"
  - name: minikube
    url: "https://storage.googleapis.com/minikube/releases/{{ versions['minikube'] }}/minikube-{{ os }}-amd64"
    checksum: "sha256:3121f933bf8d608befb24628a045ce536658738c14618504ba46c92e656ea6b5"
  - name: mkcert
    url: "https://github.com/FiloSottile/mkcert/releases/download/{{ versions['mkcert'] }}/mkcert-{{ versions['mkcert'] }}-{{ os }}-amd64"
  - name: spruce
    url: "https://github.com/geofffranks/spruce/releases/download/{{ versions['spruce'] }}/spruce-{{ os }}-amd64"
  - name: stern
    url: "https://github.com/wercker/stern/releases/download/{{ versions['stern'] }}/stern_{{ os }}_amd64"
    checksum: "sha256:e0b39dc26f3a0c7596b2408e4fb8da533352b76aaffdc18c7ad28c833c9eb7db"

  archives:
    - name: gcloud
      url: "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ versions['gcloud'] }}-{{ os }}-x86_64.tar.gz"
      format: tar.gz
      checksum: "sha256:3ee929cb236cc3a0c1d30dba514df198951f13681523bb3149ac6eb28af46443"
    - name: helm
      url: "https://get.helm.sh/helm-{{ versions['helm'] }}-{{ os }}-amd64.tar.gz"
      format: tar.gz
      checksum: "sha256:e6be589df85076108c33e12e60cfb85dcd82c5d756a6f6ebc8de0ee505c9fd4c"
    - name: kubectx
      url: "https://github.com/ahmetb/kubectx/archive/{{ versions['kubectx'] }}.tar.gz"
      format: tar.gz
    - name: kubeps1
      url: "https://github.com/jonmosco/kube-ps1/archive/{{ versions['kubeps1'] }}.tar.gz"
      format: tar.gz
    - name: terraform
      url: "https://releases.hashicorp.com/terraform/{{ versions['terraform'] }}/terraform_{{ versions['terraform'] }}_{{ os }}_amd64.zip"
      format: zip
      checksum: "sha256:602d2529aafdaa0f605c06adb7c72cfb585d8aa19b3f4d8d189b42589e27bf11"
    - name: vault
      url: "https://releases.hashicorp.com/vault/{{ versions['vault'] }}/vault_{{ versions['vault'] }}_{{ os }}_amd64.zip"
      format: zip
      checksum: "sha256:8f739c4850bab35e971e27c8120908f48f247b07717d19aabad1110e9966cded"
