cloud_tools_path: "{{ ansible_env['HOME'] }}/software/cloud"

os: linux
arch: amd64
arch_alt: x86_64

versions:
  aws: awscli-exe-linux-x86_64.zip
  amtool: 0.25.0
  dive: 0.11.0
  docker-compose: v2.19.1
  gcloud: 437.0.1
  helm: v3.12.1
  hugo: 0.115.2
  kubectl: v1.27.3
  kubeps1: v0.7.0
  kubie: v0.19.3
  logcli: v2.8.2
  minikube: v1.30.1
  mkcert: v1.4.4
  promtool: 2.45.0
  rbac-lookup: 0.10.1
  steampipe: v0.20.8
  stern: 1.25.0
  spruce: v1.30.2
  vault: 1.4.2

tools:
  binaries:
  - name: kubectl
    url: "https://dl.k8s.io/release/{{ versions['kubectl'] }}/bin/{{ os }}/{{ arch }}/kubectl"
  - name: kubie
    url: "https://github.com/sbstp/kubie/releases/download/{{ versions['kubie'] }}/kubie-{{ os }}-{{ arch }}"
  - name: minikube
    url: "https://storage.googleapis.com/minikube/releases/{{ versions['minikube'] }}/minikube-{{ os }}-{{ arch }}"
#    checksum: "sha256:0b07a295d5110dc70907e4660429b8f9b3e8c05119e42f73e192b5313695a913"
  - name: mkcert
    url: "https://github.com/FiloSottile/mkcert/releases/download/{{ versions['mkcert'] }}/mkcert-{{ versions['mkcert'] }}-{{ os }}-{{ arch }}"
  - name: spruce
    url: "https://github.com/geofffranks/spruce/releases/download/{{ versions['spruce'] }}/spruce-{{ os }}-{{ arch }}"
  #    checksum: "sha256:e0b39dc26f3a0c7596b2408e4fb8da533352b76aaffdc18c7ad28c833c9eb7db"
  - name: cht.sh
    url: "https://cht.sh/:cht.sh"
  - name: docker-compose
    url: "https://github.com/docker/compose/releases/download/{{ versions['docker-compose'] }}/docker-compose-{{ os }}-{{ arch_alt }}"
  - name: rbiam
    url: "https://github.com/mhausenblas/rbIAM/releases/latest/download/rbiam-{{ os }}"
  - name: container-diff
    url: "https://storage.googleapis.com/container-diff/latest/container-diff-{{ os }}-{{ arch }}"

  archives:
    - name: gcloud
      url: "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ versions['gcloud'] }}-{{ os }}-{{ arch_alt }}.tar.gz"
      format: tar.gz
#      checksum: "sha256:3ee929cb236cc3a0c1d30dba514df198951f13681523bb3149ac6eb28af46443"
    - name: aws
      url: "https://awscli.amazonaws.com/{{ versions['aws'] }}"
      format: zip
    - name: helm
      url: "https://get.helm.sh/helm-{{ versions['helm'] }}-{{ os }}-{{ arch }}.tar.gz"
      format: tar.gz
#      checksum: "sha256:8eb56cbb7d0da6b73cd8884c6607982d0be8087027b8ded01d6b2759a72e34b1"
    - name: hugo
      url: "https://github.com/gohugoio/hugo/releases/download/v{{ versions['hugo']}}/hugo_{{ versions['hugo']}}_{{ os }}-{{ arch }}.tar.gz"
      format: tar.gz
    - name: kubeps1
      url: "https://github.com/jonmosco/kube-ps1/archive/{{ versions['kubeps1'] }}.tar.gz"
      format: tar.gz
    - name: vault
      url: "https://releases.hashicorp.com/vault/{{ versions['vault'] }}/vault_{{ versions['vault'] }}_{{ os }}_{{ arch }}.zip"
      format: zip
#      checksum: "sha256:f2bca89cbffb8710265eb03bc9452cc316b03338c411ba8453ffe7419390b8f1"
    - name: rbac-lookup
      url: "https://github.com/FairwindsOps/rbac-lookup/releases/download/v{{ versions['rbac-lookup'] }}/rbac-lookup_{{ versions['rbac-lookup'] }}_{{ os | capitalize }}_{{ arch_alt }}.tar.gz"
      format: tar.gz
    - name: steampipe
      url: "https://github.com/turbot/steampipe/releases/download/{{ versions['steampipe'] }}/steampipe_{{ os }}_{{ arch }}.tar.gz"
      format: tar.gz
    - name: dive
      url: "https://github.com/wagoodman/dive/releases/download/v{{ versions['dive'] }}/dive_{{ versions['dive'] }}_{{ os }}_{{ arch }}.tar.gz"
      format: tar.gz
    - name: logcli
      url: "https://github.com/grafana/loki/releases/download/{{ versions['logcli'] }}/logcli-{{ os }}-{{ arch }}.zip"
      format: zip
    - name: promtool
      url: "https://github.com/prometheus/prometheus/releases/download/v{{ versions['promtool'] }}/prometheus-{{ versions['promtool'] }}.{{ os }}-{{ arch }}.tar.gz"
      format: tar.gz
    - name: amtool
      url: "https://github.com/prometheus/alertmanager/releases/download/v{{ versions['amtool'] }}/alertmanager-{{ versions['amtool'] }}.{{ os }}-{{ arch }}.tar.gz"
      format: tar.gz
    - name: stern
      url: "https://github.com/stern/stern/releases/download/v{{ versions['stern'] }}/stern_{{ versions['stern'] }}_{{ os }}_{{ arch }}.tar.gz"
      format: tar.gz
